=== Martin-Spamer/java-coaching/src/test/resources/Scheduler.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/MainApp.dtd

   	An example how to use this DTD from your XML document:

    <!DOCTYPE Scheduler SYSTEM "Scheduler.dtd">
    <Scheduler>
    	<command name="" class="">
    		<parameter name="" value=""/>
    	</command>
    	
    	<thread name="" class="">
    		<parameter name="" value=""/>    	
    	</thread>
    </Scheduler>
-->

<!ELEMENT scheduler (command|thread)*>

<!ELEMENT command (parameter)*>
<!ATTLIST command name CDATA #IMPLIED>
<!ATTLIST command class CDATA #IMPLIED>

<!ELEMENT thread (parameter)*>
<!ATTLIST thread name CDATA #IMPLIED>
<!ATTLIST thread class CDATA #IMPLIED>

<!ELEMENT parameter >
<!ATTLIST parameter name CDATA #IMPLIED>
<!ATTLIST parameter value CDATA #IMPLIED>

=== Martin-Spamer/java-coaching/src/test/resources/ExampleScheduler.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
	<!DOCTYPE scheduler SYSTEM "Scheduler.dtd">
-->
<scheduler>
	<thread name="Process Alice" class="coaching.thread.ProcessAlice" />
	<thread name="Process Bob" class="coaching.thread.ProcessBob" ></thread>
	<thread name="Process Charlie" class="coaching.thread.ProcessCharlie" >
    	<parameter name="name" value="value"/>
	</thread>

	<command name="CommandAlice" class="coaching.thread.CommandAlice" />
	<command name="CommandBob" class="coaching.thread.CommandBob" ></command>
	<command name="CommandCharlie" class="coaching.thread.CommandCharlie">
    	<parameter name="name" value="value"/>
	</command>

</scheduler>
