=== Martin-Spamer/java-coaching/src/main/resources/xml/rules.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    An example how to use this DTD from your XML document:

    <!DOCTYPE rules SYSTEM "rules.dtd">
    <rules>
    ...
    </rules>
-->

<!ELEMENT iteration (iteration|selection|sequence)*>

<!ELEMENT selection EMPTY>

<!ELEMENT sequence (iteration|selection|sequence)*>

<!ELEMENT rule (iteration|selection|sequence)*>
<!ATTLIST rule id CDATA #IMPLIED>
<!ATTLIST rule name CDATA #IMPLIED>

<!ELEMENT rules (rule)*>

=== Martin-Spamer/java-coaching/src/main/resources/xml/rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "rules.dtd">
<rules>
  <rule id='001' name='name'/>
  <rule>
    <sequence/>
  </rule>
  <rule>
    <selection/>
  </rule>
  <rule>
    <iteration/>
  </rule>
</rules>
